@startuml
scale 350 width
[*] --> Draft : New

Draft --> Pending : Save

state Pending {

  state "Technical Review" as TechnicalReview
  state "President Review" as PresidentoReview

  [*] --> TechnicalReview
  TechnicalReview --> PresidentReview : Reviewed by technician
  PresidentReview --> [*] : Reviewed by president
}

Approved -> [*]

@enduml